import { useEffect, useState } from 'react';
import { Alert, Button, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import * as SecureStore from 'expo-secure-store';
import * as Location from 'expo-location';
import { Session } from './types';
import { getQueueCount, getSession, initializeDatabase, saveSession } from './services/LocalDatabase';
import { api, disconnectTransport } from './services/Transport';
import DriverScreen from './screens/DriverScreen';
import ConsumerMap from './screens/ConsumerMap';
import { LOCATION_TASK } from './services/LocationTask';
import { startSyncManager } from './services/SyncManager';
export default function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [tab, setTab] = useState<'driver' | 'consumer'>('driver');
  const [token, setToken] = useState('');
  const [busy, setBusy] = useState(true);
  const [failure, setFailure] = useState<string | null>(null);
  useEffect(() => {
    void initializeDatabase().then(getSession).then(saved => {
      setSession(saved); if (saved?.role === 'consumer') setTab('consumer');
    }).catch(error => setFailure(String(error))).finally(() => setBusy(false));
  }, []);
  useEffect(() => {
    if (session?.role === 'driver') return startSyncManager();
  }, [session?.tripId, session?.role]);
  async function configure() {
    setBusy(true);
    try {
      const verified = await api<{ tripId: string; role: Session['role'] }>('/telemetry/session', {}, token.trim());
      const old = await getSession();
      const sameTrip = old?.tripId === verified.tripId && old.role === verified.role;
      if (!sameTrip && (await getQueueCount() > 0 || await Location.hasStartedLocationUpdatesAsync(LOCATION_TASK))) {
        throw new Error('Stop tracking and sync saved points before switching trips. You can renew the current trip credential.');
      }
      const value: Session = { ...verified, simulateOffline: sameTrip ? old.simulateOffline : false };
      // Validate first; a pasted credential for another trip must never replace
      // the token used by a concurrent background upload of the active trip.
      await SecureStore.setItemAsync('trip-token', token.trim());
      await saveSession(value); disconnectTransport(); setSession(value); setToken('');
      setTab(value.role === 'driver' ? 'driver' : 'consumer');
    } catch (error) {
      Alert.alert('Session failed', error instanceof Error ? error.message : String(error));
    } finally { setBusy(false); }
  }
  async function changeCredential() {
    // Retain the old session/credential on disk until replacement validates.
    setSession(null);
  }
  return <SafeAreaProvider><SafeAreaView style={styles.page}>
    {failure ? <Text style={styles.error}>{failure}</Text> : !session ? <ScrollView contentContainerStyle={styles.setup}>
      <Text style={styles.title}>NexusFleet</Text>
      <Text>Paste the driver or consumer credential generated by the backend provisioning command.</Text>
      <TextInput value={token} onChangeText={setToken} placeholder="Trip JWT" secureTextEntry autoCapitalize="none"
        autoCorrect={false} style={styles.input} />
      <Button title={busy ? 'Loading…' : 'Connect to trip'} disabled={busy || !token.trim()} onPress={() => { void configure(); }} />
    </ScrollView> : <>
      <View style={styles.tabs}>
        {session.role === 'driver' && <Button title="Driver" onPress={() => setTab('driver')} />}
        <Button title="Consumer map" onPress={() => setTab('consumer')} />
        <Button title="Credential" onPress={() => { void changeCredential().catch(error => Alert.alert('NexusFleet', String(error))); }} />
      </View>
      {tab === 'driver' ? <ScrollView><DriverScreen /></ScrollView> : <ConsumerMap session={session} />}
    </>}
  </SafeAreaView></SafeAreaProvider>;
}
const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F5F7FA' }, setup: { padding: 24, gap: 24 },
  title: { fontSize: 36, fontWeight: '700' }, tabs: { flexDirection: 'row', justifyContent: 'space-around', padding: 10 },
  input: { borderColor: '#9AA4B2', borderWidth: 1, borderRadius: 8, padding: 14 }, error: { padding: 24, color: '#B3261E' },
});
